# Generated by Django 2.2.13 on 2021-06-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialskills',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
