# Generated by Django 2.2.13 on 2021-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('experience', models.CharField(max_length=250)),
            ],
        ),
    ]
