# Generated by Django 2.2.13 on 2021-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
