# Generated by Django 2.2.13 on 2021-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
